# Generated by Django 2.1.5 on 2019-01-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0002_auto_20190126_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='id',
            field=models.AutoField(auto_created=True, default=' ', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance_policy_id',
            field=models.CharField(max_length=120),
        ),
    ]
