# Generated by Django 2.1.5 on 2019-01-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190125_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='postcode',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
